live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x1e2127"
blue = "0x41a7fc"
cyan = "0x34bfd0"
green = "0x8bcd5b"
magenta = "0xc75ae8"
red = "0xf65866"
white = "0x828791"
yellow = "0xefbd5d"

[colors.dim]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x828791"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2127"
blue = "0x41a7fc"
cyan = "0x34bfd0"
green = "0x8bcd5b"
magenta = "0xc75ae8"
red = "0xf65866"
white = "0x828791"
yellow = "0xefbd5d"

[colors.primary]
background = "0x1e2127"
bright_foreground = "0x455574"
foreground = "0x93a4c3"

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.offset]
x = -1
y = 0

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "C"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mode = "Vi|~Search"
mods = "Control"

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 200
lines = 50

[window.padding]
x = 25
y = 25
