kind: pipeline
name: test build image

steps:
  - name: build image
    image: plugins/docker
    settings:
      repo: laznp/dotfiles
      tags: latest
      username:
        from_secret: docker_user
      password:
        from_secret: docker_password

