require('settings')
require('plugins')
require('keybinds')
-- require('config.onedark')
require('config.catppuccin')
require('config.gitsigns')
require('config.colorizer')
require('config.autopair')
require('config.commenter')
require('config.toggleterm')
require('config.fzflua')
require('config.nvimtree')
require('config.bufferline')
require('config.lualine')
require('config.nodemcu')
require('config.kubectl')
require('config.treesitter')
require('config.bufdel')
require('config.ibl')
require('config.nvim-tmux')
-- require('config.finecmdline')
require('config.lsp.cmp')
require('config.lsp.servers')
