#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9
bspc monitor eDP-1 -d 0

bspc config border_width			1
bspc config window_gap				10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-1)

bspc config focused_border_color "#61AFEF"
bspc config normal_border_color "#353b45"


bspc rule -a Brave-browser:brave-browser desktop='^1' monitor='^1'
bspc rule -a Google-chrome:google-chrome desktop='^1' monitor='^1'
bspc rule -a Alacritty desktop='^2' monitor='^1'
bspc rule -a Lens desktop='^3' monitor='^1'
bspc rule -a "VirtualBox Manager" desktop='^3' monitor='^1'
bspc rule -a TelegramDesktop desktop='^5' monitor='^1'

# Polybar
$HOME/.config/polybar/launch.sh

# Libinput gesture
libinput-gestures-setup start

# TLP
sudo tlp start

# Xrandr
xrandr --auto --output HDMI-1 --mode 1920x1080 --rate 75 --left-of eDP-1

# Dunst
dunst -config ~/.config/dunst/dunstrc

# Background with Feh
pgrep -x feh > /dev/null || feh --bg-scale $HOME/.wallpaper.png &

# Picom Compositor
pgrep -x picom > /dev/null || picom --config $HOME/.config/picom/picom.conf &

# Start Spotify
spotify &
wmctrl -r Spotify -t 5

