#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9
bspc monitor eDP-1 -d 0

bspc config border_width			1
bspc config window_gap				10
bspc config split_ratio				0.50
bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config focused_border_color	"#5C6370"
bspc config normal_border_color		"#1d2127"
bspc config focus_follows_pointer	false

bspc rule -a Brave-browser:brave-browser desktop='^1' monitor='^1'
bspc rule -a Google-chrome:google-chrome desktop='^1' monitor='^1'
bspc rule -a Alacritty desktop='^2' monitor='^1'
bspc rule -a Lens desktop='^3' monitor='^1'
bspc rule -a Insomnia desktop='^3' monitor='^1'
bspc rule -a "VirtualBox Manager" desktop='^3' monitor='^1'
bspc rule -a TelegramDesktop desktop='^5' monitor='^1'
bspc rule -a "Thunar" desktop='^9' monitor='^1'

# Polybar
$HOME/.config/polybar/launch.sh

# Libinput gesture
libinput-gestures-setup start

# TLP
sudo tlp start

# Xrandr
xrandr --auto --output HDMI-1 --mode 1920x1080 --rate 75 --left-of eDP-1

# Dunst
dunst -config ~/.config/dunst/dunstrc

# Background with Feh
pgrep -x feh > /dev/null || feh --bg-scale $HOME/.wallpaper.png &

# Picom Compositor
pgrep -x picom > /dev/null || picom --config $HOME/.config/picom/picom.conf &

# Start Spotify
spotify &
wmctrl -r Spotify -t 5

