#!/usr/bin/env bash

XF86Audio{Play,Pause,Next,Prev}
    dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.{Play,Pause,Next,Previous}

# MEDIA KEYS TO SET VOLUME
XF86Audio{LowerVolume,RaiseVolume,Mute}
    $HOME/.local/custom-bin/volume {down,up,mute}

# MEDIA KEY TO PLAY / PAUSE, NEXT, PREVIOUS
super + ctrl + {Left,Right,space}
    playerctl {previous,next,play-pause} -p spotify


# RELOAD BSPWM
super + shift + r
    bspc wm -r

# CLOSE AND KILL PROGRAM
super + shift + q
    bspc node -c

# SET WINDOWS FLOATING
# super + f
	# bspc node focused -t \~floating

# SWAP / FOCUS NODE POSITION
super + {_,shift} + {h,j,k,l}
    bspc node -{f,s} {west,south,north,east}

# FOCUS / APPS TO ANOTHER DESKTOP
super + {_,shift} + {x,c,v,s,d,f,w,e,r,t}
    bspc {desktop -f,node -d} '^{1,2,3,4,5,6,7,8,9,10}'
    
# APPLICATION LAUNCHER KEYBIND
# TERMINAL EMULATOR
super + Return
    alacritty -t "Alacritty"

# ROFI PROGRAM LAUNCHER
super + space
    rofi -no-lazy-grab -no-history -no-sort -show drun -modi ssh,drun,calc -theme /home/laznp/.config/rofi/config

# Print
Print
    bash ~/.local/custom-bin/screenshot

# AUDIO OUTPUT MENU
super + shift + a
    bash ~/.local/custom-bin/audio-output

# STATUS MENU
# super + shift + s
    # bash ~/.local/custom-bin/statusmenu

# POWER MENU
super + shift + z
    bash ~/.local/custom-bin/powermenu

# PASSWORD MENU
super + shift + p
    bash ~/.local/custom-bin/passwordmenu

# WINDOW SWITCHER
super + Tab
    rofi -modi window -show window -theme ~/.config/rofi/card_square.rasi

# LOCKSCREEN
ctrl + super + l
   betterlockscreen -l dimblur

