#!/usr/bin/env bash

# MEDIA KEYS TO SET VOLUME
#XF86Audio{Play,Pause,Next,Prev}
#    dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.{Play,Pause,Next,Previous}

#alt + F1
#	~/.local/bin/volume mute
	# pactl set-sink-mute @DEFAULT_SINK@ toggle

#alt + ctrl + {Down,Up}
#	~/.local/bin/volume {down,up}
	# pactl {set-sink-volume @DEFAULT_SINK@ -5%,set-sink-volume @DEFAULT_SINK@ +5%}

# MEDIA KEY TO PLAY / PAUSE, NEXT, PREVIOUS
#alt + ctrl + {Left,Right,space}
#	playerctl {previous,next,play-pause} -p spotify

# MEDIA KEY TO SET BRIGHTNESS
#alt + ctrl + {Prior,Next}
#    sudo xbacklight {-inc,-dec} 10

# RELOAD SXHKD
alt + ctrl + Escape
	pkill -USR1 -x sxhkd ; notify-send 'SXHKD' 'Config Reloaded.'

# RELOAD BSPWM
alt + shift + r
	bspc wm -r

# POWERMENU
alt + shift + e
	bash $HOME/.config/rofi/powermenu.sh

# CLOSE AND KILL PROGRAM
alt + shift + q
	bspc node -c

# SET WINDOWS MONOCLE FULLSCREEN
alt + f
    bspc desktop -l next

# SET WINDOWS FLOATING
alt + shift + {f,a}
	bspc node -t {floating,tiled}

# SWAP / FOCUS NODE POSITION
alt + {_,shift} + {h,j,k,l}
	bspc node -{f,s} {west,south,north,east}
alt + {_,shift} + {Left,Down,Up,Right}
	bspc node -{f,s} {west,south,north,east}

# FOCUS / APPS TO ANOTHER DESKTOP
alt + {_,shift} + {1-9,0}
    bspc {desktop -f,node -d} '^{1-9,10}'

# SWAP / FOCUS ANOTHER DESKTOP
ctrl + {Left,Right}
	bspc desktop -f {prev,next}
alt + button{4,5}
	bspc desktop -f {prev,next}

# EXPAND WINDOWS
super + alt + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# SHRINK WINDOWS
super + alt + shift + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# MOVE FLOATING WINDOWS
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

# APPLICATION LAUNCHER KEYBIND
# TERMINAL EMULATOR
alt + Return
	alacritty -t "Alacritty"

# ROFI PROGRAM LAUNCHER
# alt + space
	# rofi -no-lazy-grab -no-history -no-sort -show drun -modi ssh,drun,calc -theme /home/laznp/.config/rofi/config

alt + space
    dmenu_run

#alt + shift + n
#	alacritty -t "Ranger" -e "ranger"

#Print
#	import png:- | xclip -selection clipboard -t image/png -filter && notify-send Screenshot 'Saved to clipboard.'

#alt + c
#    ~/.local/bin/scratchpad Spotify spotify

# LOCKSCREEN
#super + l
#    betterlockscreen -l dimblur

