#!/usr/bin/env bash

XF86Audio{Play,Pause,Next,Prev}
    dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.{Play,Pause,Next,Previous}

# MEDIA KEYS TO SET VOLUME
XF86Audio{LowerVolume,RaiseVolume,Mute}
    $HOME/.local/bin/volume {down,up,mute}
    # pactl {set-sink-volume @DEFAULT_SINK@ -5%,set-sink-volume @DEFAULT_SINK@ +5%,set-sink-mute @DEFAULT_SINK@ toggle}

# MEDIA KEY TO PLAY / PAUSE, NEXT, PREVIOUS
super + ctrl + {Left,Right,space}
	playerctl {previous,next,play-pause} -p spotify

# RELOAD SXHKD
super + ctrl + Escape
	pkill -USR1 -x sxhkd ; notify-send 'SXHKD' 'Config Reloaded.'

# RELOAD BSPWM
super + shift + r
	bspc wm -r

# POWERMENU
super + shift + e
	bash $HOME/.config/rofi/powermenu.sh

# CLOSE AND KILL PROGRAM
super + shift + q
	bspc node -c

# SET WINDOWS MONOCLE FULLSCREEN
super + f
    bspc desktop -l next

# SET WINDOWS FLOATING
super + shift + {f,a}
	bspc node -t {floating,tiled}

# SWAP / FOCUS NODE POSITION
super + {_,shift} + {h,j,k,l}
	bspc node -{f,s} {west,south,north,east}
super + {_,shift} + {Left,Down,Up,Right}
	bspc node -{f,s} {west,south,north,east}

# FOCUS / APPS TO ANOTHER DESKTOP
super + {_,shift} + {1-9,0}
    bspc {desktop -f,node -d} '^{1-9,10}'

# SWAP / FOCUS ANOTHER DESKTOP
ctrl + {Left,Right}
	bspc desktop -f {prev,next}
super + button{8,9}
	bspc desktop -f {prev,next}

# EXPAND WINDOWS
super + alt + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# SHRINK WINDOWS
super + alt + shift + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# MOVE FLOATING WINDOWS
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

# APPLICATION LAUNCHER KEYBIND
# TERMINAL EMULATOR
super + Return
	alacritty -t "Alacritty"

# ROFI PROGRAM LAUNCHER
super + space
    rofi -no-lazy-grab -no-history -no-sort -show drun -modi ssh,drun,calc -theme /home/laznp/.config/rofi/config

Print
    import png:- | xclip -selection clipboard -t image/png -filter && notify-send Screenshot 'Saved to clipboard.'

#alt + c
#    ~/.local/bin/scratchpad Spotify spotify

# LOCKSCREEN
ctrl + super + l
   betterlockscreen -l dimblur

