#!/usr/bin/env bash

# MEDIA KEYS TO SET VOLUME
super + {F1,F2,F3}
	{pactl set-sink-mute @DEFAULT_SINK@ toggle,pactl set-sink-volume @DEFAULT_SINK@ -5%,pactl set-sink-volume @DEFAULT_SINK@ +5%}

# MEDIA KEY TO PLAY / PAUSE, NEXT, PREVIOUS
ctrl + super + {Left,Right,space}
	playerctl {previous,next,play-pause}

# RELOAD SXHKD
super + Escape
	pkill -USR1 -x sxhkd ; notify-send 'SXHKD' 'Config Reloaded.'

# RELOAD BSPWM
super + shift + r
	bspc wm -r

# POWERMENU
super + shift + e
	bash $HOME/.config/rofi/powermenu.sh

# CLOSE AND KILL PROGRAM
super + shift + q
	bspc node -k

# SET WINDOWS FULLSCREEN
super + f
	bspc node -t fullscreen

# SET WINDOWS TILED
super + shift + f
	bspc node -t tiled

# SET WINDOWS FLOATING
super + shift + a
	bspc node -t floating

# SWAP / FOCUS NODE POSITION
super + {_,shift} + {h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

super + {_,shift} + {Left,Down,Up,Right}
	bspc node -{f,s} {west,south,north,east}


# FOCUS / APPS TO ANOTHER DESKTOP
super + {_,shift} + {1-9,0}
    bspc {desktop -f,node -d} '^{1-9,10}'

# FOCUS ANOTHER MONITOR BY ARROW
alt + {Left,Right}
	bspc monitor {west,east} -f

# EXPAND WINDOWS
super + alt + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# SHRINK WINDOWS
super + alt + shift + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# MOVE FLOATING WINDOWS
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

# APPLICATION LAUNCHER KEYBIND
# TERMINAL EMULATOR
super + Return
	alacritty

# ROFI PROGRAM LAUNCHER
super + @space
	rofi -no-lazy-grab -no-history -no-sort -show drun -modi ssh,drun,calc -theme /home/laznp/.config/rofi/config

super + shift + n
	alacritty -e "ranger"

Print
	import png:- | xclip -selection clipboard -t image/png -filter && notify-send Screenshot 'Saved to clipboard.'

