#!/usr/bin/env bash

# SXHKD
pgrep -x sxhkd > /dev/null || killall sxhkd || sxhkd &

# Set Natural Scrolling
xinput | grep -e "Razer Razer Basilisk Ultimate Dongle" | grep pointer | awk -F '=' '{ print $2 }' | awk '{ print $1 }' | while read line; do xinput set-prop $line "libinput Natural Scrolling Enabled" 1; done
xinput | grep -e "Razer Razer Basilisk Ultimate Dongle" | grep pointer | awk -F '=' '{ print $2 }' | awk '{ print $1 }' | while read line; do xinput set-prop $line "libinput Accel Profile Enabled" 0, 1; done
xinput | grep -e "Razer Basilisk Ultimate" | grep pointer | awk -F '=' '{ print $2 }' | awk '{ print $1 }' | while read line; do xinput set-prop $line "libinput Natural Scrolling Enabled" 1; done
xinput | grep -e "Razer Basilisk Ultimate" | grep pointer | awk -F '=' '{ print $2 }' | awk '{ print $1 }' | while read line; do xinput set-prop $line "libinput Accel Profile Enabled" 0, 1; done

# Turn on RAM LED
openrgb -d 'Corsair Dominator Platinum' -m Direct -c '6478fa'

# Set Cursor
xsetroot -cursor_name left_ptr &

# Swap Alt to Super
setxkbmap -option altwin:swap_lalt_lwin

# Launch Compositor, Wallpaper, Polybar
pgrep -x picom > /dev/null || picom --config $HOME/.config/picom/picom.conf &
pgrep -x feh > /dev/null || feh --bg-scale $HOME/.wallpaper.png $HOME/.wallpaper-portrait.png &
$HOME/.config/polybar/launch.sh
