#!/usr/bin/env bash
export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"
export BSPWM_STATE="${XDG_DATA_HOME:-$HOME/.local/share}/bspwm-state.json"

# SXHKD
pgrep -x sxhkd > /dev/null || killall sxhkd || sxhkd &

# Set Default Cursor
xsetroot -cursor_name left_ptr &

# Set Natural Scrolling
xinput | grep -e "Razer Razer Basilisk Ultimate Dongle" | grep pointer | awk -F '=' '{ print $2 }' | awk '{ print $1 }' | while read line; do xinput set-prop $line "libinput Natural Scrolling Enabled" 1; done
xinput | grep -e "Razer Razer Basilisk Ultimate Dongle" | grep pointer | awk -F '=' '{ print $2 }' | awk '{ print $1 }' | while read line; do xinput set-prop $line "libinput Accel Profile Enabled" 0, 1; done
xinput | grep -e "Razer Basilisk Ultimate" | grep pointer | awk -F '=' '{ print $2 }' | awk '{ print $1 }' | while read line; do xinput set-prop $line "libinput Natural Scrolling Enabled" 1; done
xinput | grep -e "Razer Basilisk Ultimate" | grep pointer | awk -F '=' '{ print $2 }' | awk '{ print $1 }' | while read line; do xinput set-prop $line "libinput Accel Profile Enabled" 0, 1; done

# Turn on RAM LED
openrgb -d 'Corsair Dominator Platinum' -m Direct -c '6478fa'

# Set Cursor
xsetroot -cursor_name left_ptr &

# Swap Alt to Super
setxkbmap -option altwin:swap_lalt_lwin

# Launch Compositor, Wallpaper, Polybar
pgrep -x picom > /dev/null || picom --config $HOME/.config/picom/picom.conf &
pgrep -x feh > /dev/null || feh --bg-scale $HOME/.wallpaper.png $HOME/.wallpaper-portrait.png &
$HOME/.config/polybar/launch.sh

# Multiple Monitor Config
if [ "$(xrandr -q | grep 'HDMI-A-0' | awk '{ print $2}')" == 'connected' ]; then
    xrandr --output DisplayPort-0 --primary --mode 2560x1440 --rate 75 --pos 0x0 --rotate normal \
      --output HDMI-1 --mode 1920x1080 --rate 75 --rotate left --left-of DP-1
    bspc monitor DP-1 -d 1 2 3 4 5 6
    bspc monitor HDMI-1 -d 7 8 9
    bspc wm --reorder-monitors DP-1 HDMI-1
else
    xrandr --output DisplayPort-0 --primary --mode 2560x1440 --rate 75 --pos 0x0 --rotate normal --set TearFree on
    bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9
    bspc wm --reorder-monitors DisplayPort-0
fi

# BSPWM Config
bspc config border_width			2
bspc config window_gap				15
bspc config split_ratio				0.50
bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config focused_border_color	"#1E2127"
bspc config normal_border_color		"#6e6e6e"
bspc config focus_follows_pointer	false
bspc config remove_disabled_monitor true
bspc config pointer_motion_interval 7ms

# Workspace Rule Config
bspc rule -a firefox:Navigator desktop='^1' monitor='^2'
bspc rule -a Brave-browser:brave-browser desktop='^1'
bspc rule -a Alacritty desktop='^2'
bspc rule -a Subl:subl desktop='^3'
bspc rule -a VSCodium:vscodium desktop='^3'
bspc rule -a OpenLens:openlens desktop='^4'
bspc rule -a Lens:lens desktop='^4'
bspc rule -a Spotify:spotify desktop='^5'
bspc rule -a Lutris:lutris desktop='^6'
bspc rule -a "Microsoft Teams - Preview":"microsoft teams - preview" desktop='^7'
bspc rule -a Slack:slack desktop='^8'
bspc rule -a TelegramDesktop:telegram-desktop desktop='^9'
bspc rule -a Google-chrome:web.whatsapp.com desktop='^9'
bspc rule -a *:*:'meet.google.com is sharing your screen.' hidden=true

# Launch Application
pgrep -x corectrl || corectrl &
pgrep -x telegram-desktop || telegram-desktop &

# Notify Reload
notify-send "BSPWM" "Config Reloaded!"
