#!/usr/bin/env bash
export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"
export BSPWM_STATE="${XDG_DATA_HOME:-$HOME/.local/share}/bspwm-state.json"

bash $HOME/.config/bspwm/autostart
bash $HOME/.config/bspwm/monitor-config
bash $HOME/.config/bspwm/general-config
bash $HOME/.config/bspwm/workspace-rule-config

# Launch Application
pgrep -x corectrl || corectrl &
pgrep -x telegram-desktop || telegram-desktop &
pgrep -x whatsie || whatsie &

# Notify Reload
notify-send "BSPWM" "Config Reloaded!"
