#!/usr/bin/env bash

bspc config border_width			2
bspc config window_gap				15
bspc config split_ratio				0.50
bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config focused_border_color	"#1E2127"
bspc config normal_border_color		"#6e6e6e"
bspc config focus_follows_pointer	false
bspc config remove_disabled_monitor true
bspc config pointer_motion_interval 7ms