#!/usr/bin/env bash

if [ "$(xrandr -q | grep 'HDMI-A-0' | awk '{ print $2}')" == 'connected' ]; then
    xrandr --output DisplayPort-0 --primary --mode 2560x1440 --rate 75 --pos 0x0 --rotate normal \
      --output HDMI-1 --mode 1920x1080 --rate 75 --rotate left --left-of DP-1
    bspc monitor DP-1 -d 1 2 3 4 5 6
    bspc monitor HDMI-1 -d 7 8 9
    bspc wm --reorder-monitors DP-1 HDMI-1
else
    xrandr --output DisplayPort-0 --primary --mode 2560x1440 --rate 75 --pos 0x0 --rotate normal --set TearFree on
    bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9
    bspc wm --reorder-monitors DisplayPort-0
fi