#!/usr/bin/env bash

bspc rule -a firefox:Navigator desktop='^1' monitor='^2'
bspc rule -a Brave-browser:brave-browser desktop='^1'
bspc rule -a Alacritty desktop='^2'
bspc rule -a Subl:subl desktop='^3'
bspc rule -a VSCodium:vscodium desktop='^3'
bspc rule -a OpenLens:openlens desktop='^4'
bspc rule -a Lens:lens desktop='^4'
bspc rule -a Spotify:spotify desktop='^5'
bspc rule -a Lutris:lutris desktop='^6'
bspc rule -a "Microsoft Teams - Preview":"microsoft teams - preview" desktop='^7'
bspc rule -a Slack:slack desktop='^8'
bspc rule -a TelegramDesktop:telegram-desktop desktop='^9'
bspc rule -a WhatSie:whatsie desktop='^9'
bspc rule -a *:*:'meet.google.com is sharing your screen.' hidden=true