#!/bin/bash

items=$(rbw ls)
selection=$(echo "$items" | rofi -dmenu -p "  " -theme ~/.config/rofi/config -i)
[ -z "$selection" ] && exit 0

field=$(printf "Username\nTOTP\nPassword" | rofi -dmenu -theme ~/.config/rofi/card_square.rasi -selected-row 1 -theme-str 'window { width: 15em; }' -no-sort -no-lazy-grab -no-history)
[ -z "$field" ] && exit 0

# Step 3: Retrieve and copy to clipboard
case "$field" in
  Username)
    value=$(rbw get "$selection" --field username)
    ;;
  Password)
    value=$(rbw get "$selection")
    ;;
  TOTP)
    value=$(rbw get "$selection" --field totp)
    ;;
  *)
    notify-send "Bitwarden" "Invalid selection."
    exit 1
    ;;
esac

echo -n "$value" | xclip -selection clipboard

notify-send "Bitwarden" "$field for $selection copied to clipboard."
