#!/usr/bin/env bash

rofi_command="rofi -theme $HOME/.config/rofi/card_square"

# Options
area_save_cl="🖼️ Area   󱉥"
area_cl="  Area   󰅇"
full_save_cl="🖼️ Screen   󱉥"
full_cl="  Screen   󰅇"

# Variable passed to rofi
options="$full_save_cl\n$full_cl\n$area_cl\n$area_save_cl"

chosen="$(echo -e "$options" | $rofi_command -lines 3 -dmenu -selected-row 2)"
case $chosen in
    $area_save_cl)
        sleep 0.25
        maim --hidecursor --select  "$HOME/Pictures/$(date +'%Y-%m-%d_%H-%M').png"
        flameshot gui
        notify-send --app-name="screenshot" "Screenshot" "Area saved and copied to clipboard"
        ;;
    $area_cl)
        sleep 0.25
        #maim --hidecursor --select | xclip -selection clipboard -t image/png
        flameshot gui --clipboard
        notify-send --app-name="screenshot" "Screenshot" "Area copied to clipboard"
        ;;
    $full_save_cl)
        sleep 0.25
        maim --hidecursor --select  "$HOME/Pictures/$(date +'%Y-%m-%d_%H-%M').png"
        notify-send --app-name="screenshot" "Screenshot" "Screen saved and copied to clipboard"
        ;;
    $full_cl)
        sleep 0.25
        maim --hidecursor | xclip -selection clipboard -t image/png
        notify-send --app-name="screenshot" "Screenshot" "Screen copied to clipboard"
        ;;
esac
