context.objects = [
    {
        factory = adapter
        args = {
            factory.name     = support.null-audio-sink
            node.name        = "sunshine-stream"
            node.description = "Sunshine Stream"
            media.class      = "Audio/Sink"
            audio.position   = "FL,FR"
        }
    }
]
