#!/usr/bin/env bash
export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"
export BSPWM_STATE="${XDG_DATA_HOME:-$HOME/.local/share}/bspwm-state.json"
export WINIT_UNIX_BACKEND=x11

# KeyMapper
# pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x xremap > /dev/null || xremap $HOME/.config/xremap/config.yaml &

# Polkit Agent
pgrep -xf /usr/lib/polkit-kde-authentication-agent-1 || /usr/lib/polkit-kde-authentication-agent-1 &

# OpenRGB
# openrgb -d 'Corsair Dominator Platinum' -m Direct -c 'ffffff'
# openrgb -d 4 -z 1 -s 12 -m Direct -c "FFFFFF"

# Multiple Monitor Config
xrandr --output DisplayPort-0 --primary --mode 2560x1440 --rate 75 --set TearFree on --output DisplayPort-1 --rotate left --rate 75 --left-of DisplayPort-0
bspc monitor DisplayPort-0 -d 1 2 3 4 5 6
bspc monitor DisplayPort-1 -d 7 8 9 10
bspc wm --reorder-monitors DisplayPort-0 DisplayPort-1
# xrandr --output HDMI-A-0 --primary --mode 1920x1080 --rate 75 --set TearFree on
# bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9 0

# Global X11 Initial Run
xsetroot -cursor_name left_ptr
# xsetroot -solid "#000000"
xset -dpms

# BSPWM Config
bspc config border_width			2
bspc config window_gap				15
bspc config split_ratio				0.50
bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config focused_border_color	"#eeeeee"
bspc config normal_border_color		"#6e6e6e"
bspc config focus_follows_pointer	false
bspc config pointer_motion_interval 7ms

# Workspace Rule Config
bspc rule -a firefox:Navigator desktop='^1'
# bspc rule -a Brave-browser:brave-browser desktop='^1'
bspc rule -a Google-chrome:google-chrome desktop='^1'
bspc rule -a qutebrowser:qutebrowser desktop='^1'
bspc rule -a 'Alacritty:Alacritty:Alacritty' desktop='^2'
bspc rule -a 'Alacritty:Alacritty:NeoVim' desktop='^3'
bspc rule -a VSCodium:vscodium desktop='^3'
bspc rule -a Lutris:lutris desktop='^4'
bspc rule -a bottles:bottles desktop='^4'
bspc rule -a heroic:heroic desktop='^4'
bspc rule -a steam:steamwebhelper desktop='^4'
bspc rule -a OpenLens:openlens desktop='^5'
# bspc rule -a Lens:lens desktop='^5'
bspc rule -a Bitwarden:bitwarden desktop='^6'
bspc rule -a 1Password:1password desktop='^6'
bspc rule -a "OrcaSlicer":"orca-slicer" desktop='^6'
bspc rule -a TelegramDesktop:Telegram desktop='^7'
# bspc rule -a "Google-chrome":"web.whatsapp.com" desktop='^7'
bspc rule -a "WebApp-WhatsApp6135":"Navigator" desktop='^7'
bspc rule -a "Google-chrome":"open.spotify.com" desktop='^8'
bspc rule -a Spotify:spotify desktop='^8'
bspc rule -a "WebApp-MicrosoftTeams4073":Navigator desktop='^9'
bspc rule -a Slack:slack desktop='^10'
bspc rule -a *:*:'meet.google.com is sharing your screen.' hidden=true
bspc rule -a ranger:ranger state="floating" follow="on" focus="on"
bspc rule -a Onboard:onboard state="floating" follow="on" focus="on"

# Launch Application
pgrep -x corectrl || corectrl & disown
pgrep -x slack || slack & disown
# (pgrep -f "web.whatsapp.com" > /dev/null) || google-chrome-stable --app=https://web.whatsapp.com & disown
# pgrep -x telegram-desktop || telegram-desktop &
# pgrep -x -f whatsie || whatsie &
# pgrep -x jamesdsp || jamesdsp &

# Launch Compositor, Wallpaper, Polybar
# pgrep -x picom > /dev/null || picom --config $HOME/.config/picom/picom.conf &
# pgrep -x feh > /dev/null || feh --bg-scale $HOME/.wallpaper/fantasy-landscape.jpg --no-xinerama &
# pgrep -x feh > /dev/null || feh --bg-fill $HOME/Downloads/owl.jpg --no-xinerama &
# pgrep -x feh > /dev/null || feh --bg-fill $HOME/Downloads/Wallpaper/haunted-library.png &
# pgrep -x feh > /dev/null || feh --bg-fill $HOME/.wallpaper/arch-nord-dark.png --no-xinerama &
# pgrep -x feh > /dev/null || feh --bg-scale $HOME/.wallpaper/arch-nord-dark.png --bg-fill $HOME/.wallpaper/arch-nord-dark.png &

$HOME/.config/polybar/launch.sh

# Notify Reload
notify-send "BSPWM" "Config Reloaded!"
