#!/usr/bin/env bash
export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"
export BSPWM_STATE="${XDG_DATA_HOME:-$HOME/.local/share}/bspwm-state.json"

# SXHKD
# pgrep -x sxhkd > /dev/null || killall sxhkd || sxhkd &
systemctl --user start sxhkd.service

# Set Natural Scrolling
xinput | grep -e "Razer Razer Basilisk Ultimate Dongle" | grep pointer | awk -F '=' '{ print $2 }' | awk '{ print $1 }' | while read line; do xinput set-prop $line "libinput Natural Scrolling Enabled" 1; done
xinput | grep -e "Razer Razer Basilisk Ultimate Dongle" | grep pointer | awk -F '=' '{ print $2 }' | awk '{ print $1 }' | while read line; do xinput set-prop $line "libinput Accel Profile Enabled" 0, 1; done
xinput | grep -e "Razer Basilisk Ultimate" | grep pointer | awk -F '=' '{ print $2 }' | awk '{ print $1 }' | while read line; do xinput set-prop $line "libinput Natural Scrolling Enabled" 1; done
xinput | grep -e "Razer Basilisk Ultimate" | grep pointer | awk -F '=' '{ print $2 }' | awk '{ print $1 }' | while read line; do xinput set-prop $line "libinput Accel Profile Enabled" 0, 1; done

# RAM
openrgb -d 'Corsair Dominator Platinum' -m Direct -c 'ffffff'

# GPU
openrgb -d 4 -z 1 -s 12 -m Direct -c "FFFFFF"

# Set Cursor
xsetroot -cursor_name left_ptr &

# Swap Alt to Super
#setxkbmap -option altwin:swap_lalt_lwin

# Multiple Monitor Config
# if [ "$(xrandr -q | grep 'DisplayPort-1' | awk '{ print $2}')" == 'connected' ]; then
xrandr --output DisplayPort-0 --primary --rate 75 --set TearFree on \
  --output DisplayPort-1 --rotate left --rate 75 --left-of DisplayPort-0
bspc monitor DisplayPort-0 -d 1 2 3 4 5 6
bspc monitor DisplayPort-1 -d 7 8 9 10
bspc wm --reorder-monitors DisplayPort-0 DisplayPort-1
# else
# xrandr --output DisplayPort-0 --primary --mode 2560x1440 --rate 75 --pos 0x0 --rotate normal --set TearFree on
# bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9 10
# bspc wm --reorder-monitors DisplayPort-0
# fi
# TEMP
# xrandr --output auto  --rotate n
# bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9 10
# bspc wm --reorder-monitors HDMI-A-0
# BSPWM Config
bspc config border_width			2
bspc config window_gap				10
bspc config split_ratio				0.50
bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config focused_border_color	"#eeeeee"
bspc config normal_border_color		"#6e6e6e"
bspc config focus_follows_pointer	false
bspc config remove_disabled_monitor true
bspc config pointer_motion_interval 7ms

# Workspace Rule Config
bspc rule -a firefox:Navigator desktop='^1'
bspc rule -a Brave-browser:brave-browser desktop='^1'
bspc rule -a Google-chrome:google-chrome desktop='^1'
bspc rule -a qutebrowser:qutebrowser desktop='^1'
bspc rule -a Alacritty desktop='^2'
bspc rule -a Subl:subl desktop='^3'
bspc rule -a NeoVim:NeoVim desktop='^3'
bspc rule -a VSCodium:vscodium desktop='^3'
bspc rule -a Lutris:lutris desktop='^4'
bspc rule -a bottles:bottles desktop='^4'
bspc rule -a heroic:heroic desktop='^4'
bspc rule -a steam:steamwebhelper desktop='^4'
bspc rule -a OpenLens:openlens desktop='^5'
bspc rule -a Lens:lens desktop='^5'
bspc rule -a Bitwarden:bitwarden desktop='^6'
bspc rule -a 1Password:1password desktop='^6'
bspc rule -a TelegramDesktop:telegram-desktop desktop='^7'
bspc rule -a whatsapp-nativefier-d40211:whatsapp-nativefier-d40211 desktop='^7'
bspc rule -a "Google-chrome":"open.spotify.com" desktop='^8'
bspc rule -a Spotify:spotify desktop='^8'
bspc rule -a "Microsoft Teams - Preview":"microsoft teams - preview" desktop='^9'
bspc rule -a "Google-chrome":"teams.microsoft.com" desktop='^9'
bspc rule -a Slack:slack desktop='^10'
bspc rule -a *:*:'meet.google.com is sharing your screen.' hidden=true
bspc rule -a ranger:ranger state="floating" follow="on" focus="on"

# Launch Application
#pgrep -x corectrl || corectrl &
pgrep -x telegram-desktop || telegram-desktop &
pgrep -x -f WhatsApp || whatsapp-nativefier &

# Launch Compositor, Wallpaper, Polybar
pgrep -x picom > /dev/null || picom --config $HOME/.config/picom/picom.conf &
# pgrep -x feh > /dev/null || feh --bg-scale $HOME/.wallpaper/fantasy-landscape.jpg --no-xinerama &
pgrep -x feh > /dev/null || feh --bg-fill $HOME/.wallpaper/arch-nord-dark.png --no-xinerama &
# pgrep -x feh > /dev/null || feh --bg-scale $HOME/.wallpaper/arch-nord-dark.png --bg-fill $HOME/.wallpaper/arch-nord-dark.png &
# pgrep -x feh > /dev/null || feh --bg-scale $HOME/.wallpaper.png $HOME/.wallpaper.png &
$HOME/.config/polybar/launch.sh

# Notify Reload
notify-send "BSPWM" "Config Reloaded!"
