#!/usr/bin/env bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config layout bsp
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12
yabai -m config mouse_follows_focus off
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m mouse_drop_action swap
yabai -m config window_opacity on

# yabai -m config active_window_opacity 1.0
# yabai -m config normal_window_opacity 0.9

SPACEBAR_HEIGHT=$(spacebar -m config height)
yabai -m config external_bar all:32:0

