k9s:
  liveViewAutoRefresh: true
  screenDumpDir: /home/laznp/.local/state/k9s/screen-dumps
  refreshRate: 1
  apiServerTimeout: 15s
  maxConnRetry: 5
  readOnly: false
  defaultView: "namespace"
  noExitOnCtrlC: true
  ui:
    enableMouse: true
    headless: false
    logoless: true
    noIcons: true
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
    tty: true
    hostPathVolume:
    - name: docker-socket
      mountPath: /var/run/docker.sock
      hostPath: /var/run/docker.sock
      readOnly: true
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
