require('settings')
require('plugins')
require('keybinds')
require('config.onedark')
require('config.gitsigns')
require('config.colorizer')
require('config.autopair')
require('config.commenter')
require('config.toggleterm')
require('config.fzflua')
-- require('config.nvimtree')
require('config.lualine')
require('config.tabline')
require('config.nodemcu')
require('config.kubectl')
require('config.treesitter')
require('config.lsp.cmp')
require('config.lsp.servers')
-- require('config.lsp.progress')
-- require('config.lsp.saga')
