require('settings')
require('plugins')
require('keybinds')
require('config.onedark')
require('config.toggleterm')
require('config.gitsigns')
require('config.colorizer')
require('config.treesitter')
require('config.autopair')
require('config.commenter')
require('config.fzflua')
require('config.nvimtree')
require('config.lualine')
require('config.tabline')
-- require('config.autocomplete')
--
