[colors.bright]
black = "0x93a4c3"
blue = "0x41a7fc"
cyan = "0x34bfd0"
green = "0x8bcd5b"
magenta = "0xc75ae8"
red = "0xf65866"
white = "0x828791"
yellow = "0xefbd5d"

[colors.dim]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x828791"
yellow = "0xd19a66"

[colors.normal]
# black = "0x1e2127"
black = "0x101010"
blue = "0x41a7fc"
cyan = "0x34bfd0"
green = "0x8bcd5b"
magenta = "0xc75ae8"
red = "0xf65866"
white = "0x828791"
yellow = "0xefbd5d"

[colors.primary]
# background = "0x1e2127"
background = "0x101010"
bright_foreground = "0x455574"
foreground = "0x93a4c3"
