# -*- conf -*-

term=xterm-256color

font=RobotoMono Nerd Font:style=Bold:size=9
font-bold=RobotoMono Nerd Font:style=Bold:size=9
font-italic=RobotoMono Nerd Font:style=Bold Italic:size=9
font-bold-italic=RobotoMono Nerd Font:style=Bold Italic:size=9
letter-spacing=-1
vertical-letter-offset=-1

initial-window-size-chars=200x50
pad=25x25
bold-text-in-bright=no

[environment]
TERM=xterm-256color

[colors-dark]
background=101010
foreground=93a4c3

regular0=101010
regular1=f65866
regular2=8bcd5b
regular3=efbd5d
regular4=41a7fc
regular5=c75ae8
regular6=34bfd0
regular7=828791

bright0=93a4c3
bright1=f65866
bright2=8bcd5b
bright3=efbd5d
bright4=41a7fc
bright5=c75ae8
bright6=34bfd0
bright7=828791

dim0=1e2127
dim1=e06c75
dim2=98c379
dim3=d19a66
dim4=61afef
dim5=c678dd
dim6=56b6c2
dim7=828791

[text-bindings]
\x1b\x0d=Shift+Return
